### ISSUE TITLE
Feature: Touchscreen UI

### ISSUE THREAD

**Issue by tobeehh** [alex9849/pi-cocktail-maker#10]
Really interesting and great project. I am designing an „opensource“ 3d printable housing as of now.

Would it be possible to allow for a dedicated port to show a UI with a selection of available drinks? This would make a touchscreen useful.

cheers

**Comment by alex9849** [comment]
Thanks! :)
Yes that should be possible. I would like to add something like an onboard screen too. Something simple that only gets used to order a drink. But that would require a second UI and for me personally I would need to buy a touchscreen for myself first. ^^

**Comment by alex9849** [comment]
A tutorial on how to use touchscreens has been added.
