### ISSUE TITLE
Feature: Add Option for Adafruit LED Animation when making drink

### ISSUE THREAD

**Issue by tobeehh** [alex9849/pi-cocktail-maker#11]
It would be supercool to add an option that allows to run an led strip animation during the making of the drink.

**Comment by alex9849** [comment]
I never used Adafruit before. But I saw that Adafruit runs in python. If Adafriut can be used next to Pi4J than it should be possible to implement a feature, where you could upload your Adafriut script, but for now I would see this as a low priority.

**Comment by alex9849** [comment]
I'm currently working on this feature. I'll implement it as part of the event system.
You'll be able to upload python scripts that will get executed by the application:
https://github.com/alex9849/pi-cocktail-maker/issues/13
