### ISSUE TITLE
Custom recipes production steps cant be combined

### ISSUE THREAD

**Issue by derekbrady** [alex9849/pi-cocktail-maker#33]
when adding new recipes  from webUI can not add them on same production step.  Can only add as individual productions steps.  (Or I am unable to)

Screenshot or pre loaded recipe---
![pre loaded](https://user-images.githubusercontent.com/35239590/219880020-c7ac2740-65a1-4b7b-93e0-8227a4dc39c8.JPG)

Screenshot of Custom added recipe--
![custom recepie](https://user-images.githubusercontent.com/35239590/219880025-04806e1c-574c-42de-a997-30b02a6073e8.JPG)

**Comment by alex9849** [comment]
You can click & hold single ingredients and drag them into other production steps. Then they get merged. I'll add some indicator symbols to make this more clear with the next update. :)

Note: Click directly on the ingredients. If you click on the production step, you'll just change the order.
