### ISSUE TITLE
Python scripts: Board library import not working

### ISSUE THREAD

**Issue by crampedTurtle** [alex9849/pi-cocktail-maker#34]
Have been looking to integrate LED lighting for the various event (start cocktail, cocktail finished) and have installed the relevant libraries from Adafruit. 

Logging within Cocktail Maker suggests the board library cannot be found, through troubleshooting it appears Cocktail Maker is calling the script with Python and not Python3 which Adafruit stipulates. 

Any chance this can be added as an option?

**Comment by tobeehh** [comment]
+1

**Comment by alex9849** [comment]
Solved with 1.0.3
